---
title: "OCR_pipeline"
author: "Matej Stevuliak"
date: "5/2/2019"
output: html_document
---

```{r setup, include=FALSE}
# Make Sure You have all following packages, If not uncoment and run next line:
#source(here('/R/src/config_file.R'))  

#library(data.table)
library(magrittr)   # Needed for pipe operator %>%  
library(tools)
library(dplyr)
library(reshape2)
library(ggplot2)
library(tidyr)      # Needed for tidy data functions like separate
library(tidyverse)
library(readxl)     # Read xlsx file
library(here)       # Used to set the path to the package dir. on the mashine 
library(knitr)      # Used for tables 
library(kableExtra)



# source the functions used in analysis
source(here('/R/src/analysis_source_functions.R'))

```


```{r}
# SET INPUT AND OUTPUT PATH
# Using function here() wil provide path to the OCR_Pipeline(package) folder on your computer,
# the input and output separate folers are in "/OCR_Pipeline/Data". 
# Recomend to move the result to different folder before every analysis.
#
# To choose different folder in your coputer as I/O folder write entire Path to the folder. 
INPUT_PATH  <- here('/Data/INPUT')
OUTPUT_PATH <- here('/Data/OUTPUT')
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# Read The the separate xlsx files from folder, Specify entire path to folder. 
 dm <- read_xlsx_set(INPUT_PATH, ".xlsx")  

```

## OCR 

# Identyfy Outliars 
Removed outliars in each iteration:
```{r echo=FALSE}
# Identify Outliars 
# DT = loaded dataframe 
# cut.well = threshold for well outliaer, 
# cut.point = threshold for point outliaer
# x = Variable: "LOCR" or "OCR" or "ECAR"

dm_r <- idfy_outliar(DT = dm, cut.well = 5, cut.point = 7, x = "LOCR" )  # could Print arguments
# write the data into file 
write_csv(dm_r, paste0(OUTPUT_PATH,"/Data_removed.csv"))  # ! clean it 
```
```{r echo=FALSE}
ggplot(dm_r, aes(Time, LOCR))+
  ggtitle("Outliar Across Samples")+
  geom_vline(xintercept = c(3.5,6.5,9.5, 12.5), linetype = "dotted")+
  geom_point(aes(Time, LOCR, color = out))+
  facet_grid(. ~  sample_id )+
  xlab("Interval Time")
```

# Procentage of  all outliars across samples 
TO DO: convert graph to aditive add legends 

```{r echo=FALSE, warning=FALSE}
dm_r <- dm_r %>% 
  mutate(out_bolean = ifelse(out == "NO", F, T))

s <- dm_r %>% 
  group_by(sample_id, out_bolean) %>% 
  summarise(n = n()) %>% 
  group_by(sample_id) %>% 
  mutate(size = sum(n), ptg = n / size *100 ) %>% 
  filter(out_bolean == T)

sw <- dm_r %>% 
  group_by(sample_id, is.out.w ) %>% 
  summarise(n_well = n()) %>% 
  group_by(sample_id) %>% 
  mutate(size = sum(n_well), ptg = n_well / size *100, Mean_int = mean(ptg) ) %>% 
  filter(is.out.w == T)

sp <- dm_r %>% 
  group_by(sample_id, is.out.p ) %>% 
  summarise(n_point = n()) %>% 
  group_by(sample_id) %>% 
  mutate(size = sum(n_point), ptg = n_point / size *100, Mean_int = mean(ptg) ) %>% 
  filter(is.out.p == T)



ggplot()+
  geom_col(aes(s$sample_id, s$ptg), fill = "green", binwidth= 0.1) + 
  geom_col(aes(sw$sample_id, sw$ptg), fill =  "blue", binwidth= 0.2) + 
  geom_col(aes(sp$sample_id, sp$ptg), fill = "red", binwidth= 0.1) + 
  coord_flip()+ 
  ylab("%") +
  xlab("sample_id")+
  ggtitle("Outliars across Samples (Not aditive)")+ 
  geom_text(aes(sw$sample_id, sw$ptg, label = paste(format(sw$ptg, digits=1, nsmall=2),"%")),
    size = 3, hjust = 1)+
   geom_text(aes(sp$sample_id, sp$ptg, label = paste(format(sp$ptg, digits=1, nsmall=2),"%")),
    size = 3, hjust = 1)+
   geom_text(aes(s$sample_id, s$ptg, label = paste(format(s$ptg, digits= 1, nsmall=2),"%")),
    size = 3, hjust = -0.01)
  

```



# Print schemes of removed points for all samples 
```{r echo=FALSE}
for (smpl in unique(dm_r$sample_id)) {
  plot <- ggplot(filter(dm_r, sample_id == smpl), aes(Time, OCR))+
            ggtitle(paste0("SAMPLE:  ", smpl))+
            geom_line(aes(group = Well)) +
            geom_point(aes(Time, OCR, color = out))+
            xlab("Interval")+
            facet_grid(Protocol  ~ . ) 
  
  print(plot)
}
```

## Bioenergetics and Estimates 
All estimates are Log transformed

# Interval estimates 

```{r warning=FALSE, include=FALSE}
b <- compute_bioenergetics(dm_r) 

```
```{r echo=FALSE}
# Print interval estimates 
b$estim %>%
  kable(digits = 3) %>%
  kable_styling(full_width = F)
```

# Error of esstimates

```{r echo=FALSE}
# ----------- Print the errors 
b$err %>%
  kable(digits = 3) %>%
  kable_styling(full_width = F)

table <- cbind(Estim = b$estim, Er = b$err)
write_csv(table, paste0(OUTPUT_PATH,"/LOCR-Estimates.csv"))

```

```{r echo=FALSE}
estim <- b$coef_melted
# Plot to show errors 
ggplot(estim)+
  ggtitle("Log Estimates of Intervals across samples")+
  geom_line(aes(Interval, Estimate, group = Sample))+
  geom_errorbar(aes(ymin = Estimate - 2*SdEr, ymax = Estimate + 2*SdEr, x = Interval), width=.2, position=position_dodge(.9)) +
  geom_text(aes(Interval, Estimate, label = paste(format(Estimate, digits=1, nsmall=1))),size = 2, vjust = -1)+
  facet_wrap(.~ Sample)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


# Bioenergetics
```{r echo=FALSE}

bio_e <- b$bio_e

bio <- melt(bio_e)
ggplot(bio)+
  ggtitle("Bio-Energetics OCR")+
  geom_boxplot(aes(variable,value))+
  geom_point(aes(variable,value, col = Sample))+
  xlab("Bio-Energetics")+
  ylab(" ")
  
write_csv(bio_e, paste0(OUTPUT_PATH,"/LOCR-BioEner.csv"))
  

```





```{r eval=FALSE, include=FALSE}
# TO DO 
# TO DO
# plot which would tell how much data suport each Estimate
# How to plot Bioenergetics ? 
# standard error ? 
ggplot(estim)+
  ggtitle("LOCR estimates line represents Sample ")
  geom_line(aes(Interval, Estimate, group = Sample))+
  geom_errorbar(aes(ymin = Estimate - 2*SdEr, ymax = Estimate + 2*SdEr, x = Interval), width=.2, position=position_dodge(.9)) 

# try to compare the samples ... 
contrast <- mean(b$estim$Int4)



```
## ECAR  

